name: C/C++ CI

on:
  push:
    branches:
      - main
jobs:
  proyecto_2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build essentials
      run: sudo apt-get install build-essential

    - name: Build and run capicua.cpp
      run: |
        g++ -o Proyecto-2/capicua Proyecto-2/capicua.cpp
        ./Proyecto-2/capicua

